version: '2'
services:
  dps:
    build: .
    command: mix start_app
    environment:
      DB_HOSTNAME: postgres
    links:
      - postgres
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
