sycclass:
  table: sycclass
  fields:
    sccscl: 
      type: text
    scclgp: 
      type: text
    scclds:
      type: text
    scclst:
      type: text
    scdlcd:
      type: text
    record_catalog:
      type: text
    record_timestamp:
      type: text
  primary_key: [sccscl, record_catalog]
  references:
    sycgroup: [scclgp, record_catalog]

sycgroup:
  table: sycgroup
  public: customer_groups
  fields: 
    sgclgp:
      type: text
    sggpds:
      type: text
    sgclcd:
      type: text
    record_catalog:
      type: text
    record_timestamp:
      type: text
  primary_key: [sgclgp, record_catalog]
  references: null

customer_groups:
  table: customer_groups
  fields:
    code: 
      type: text
      source: sgclgp
    division: 
      type: text
      source: record_catalog
    description: 
      type: text
      source: sggpds
    delete_code: 
      type: text
      source: sgclcd
  primary_key: [code, division]
  references: null

