sycclass:
  table: sycclass
  fields:
    sccscl: text
    scclgp: text
    scclds: text
    scclst: text
    scdlcd: text
    record_catalog: text
  primary_key: [sccscl, record_catalog]
  references:
    sycgroup: [scclgp, record_catalog]

sycgroup:
  table: sycgroup
  fields: 
    sgclgp: text
    sggpds: text
    sgclcd: text
    record_catalog: text
  primary_key: [sgclgp, record_catalog]
  references: null

