sycclass:
  topic: abc_sycclass
  table: customer_classes
  fields:
    code: text
    division: text
    description: text
    customer_group_code: text
    delete_code: text
    sort: text
  primary_key: [code, division]
  references:
    sycgroup: [customer_group_code, division]
  source_mapping:
    code: sccscl
    division: record_catalog
    customer_group_code: scclgp
    description: scclds
    sort: scclst
    delete_code: scdlcd

sycgroup:
  topic: abc_sycgroup
  table: customer_groups
  fields:
    code: text
    division: text
    description: text
    delete_code: text
  primary_key: [code, division]
  references: null
  source_mapping: 
    code: sgclgp
    division: record_catalog
    description: sggpds
    delete_code: sgdlcd



